name: Deploy with EC2 Runner

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted # Uses your EC2 runner
    # environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}

      - name: Deploy to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/
